# base image
FROM python:3.6.5-slim

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

#
RUN export PYTHONPATH="$PYTHONPATH:/usr/src/app"


# add app
ADD . /usr/src/app




















#FROM python:latest



#RUN mkdir -p /usr/src/app
#WORKDIR /usr/src/app
#RUN export PYTHONPATH="$PYTHONPATH:/usr/src/app"
#COPY requirements.txt /usr/src/app/
#RUN pip3 install --no-cache-dir -r requirements.txt

#ADD . /usr/src/app



