#services/users/manage.py 

import unittest
from flask.cli import FlaskGroup
# from project.app import create_app, db, mongoEngine, pyMongo
from project.app import create_app, db, mongoEngine
from project.api.models import User, Application, Application_M, User_M, Certificate_M, Accountdetails_M




app = create_app()
cli = FlaskGroup(create_app=create_app)


@cli.command()
def recreatedb():

	db.drop_all()
	db.create_all()
	db.session.commit()



@cli.command()
def test():
		tests = unittest.TestLoader().discover('project/tests', pattern='test*.py')
		result = unittest.TextTestRunner(verbosity=2).run(tests)
		if result.wasSuccessful():
			return 0
		return 1

@cli.command()
def seeddb():

	user1 = User(firstname='Tina', lastname='Prislan', email='tina.prislan@gmail.com', password='rakesh22')
	db.session.add(user1)
	# db.session.commit()

	# user = User.query.filter_by(email=user1.email).first()


	# application1 = Application(user_id=user.id,
	# 							domain='bigdata',
	# 							certificate='Certified Associate in Big Data (CABD) - Distributed Databases',
	# 							contact_firstname='Tina',
	# 							contact_lastname='Prislan',
	# 							contact_email='tina.prislan@gmail.com',
	# 							contact_streetaddress='41 Thomson Road',
	# 							contact_homecountry='Singapore',
	# 							contact_phonenumber='90900576',
	# 							contact_company_name='IKOMPASS'
	# 							)

	
	# db.session.add(application1)

	db.session.add(User(firstname='Ashwini', lastname='Rao', email='ashwini.rao@ikompass.com', password='rakesh22'))
	db.session.add(User(firstname='Deepak', lastname='G.S', email='aditya@ikompass.com', password='rakesh22'))
	db.session.add(User(firstname='Prasad', lastname='RRR', email='prasad@sugiinfotech.com', password='12345678'))

	


	db.session.commit()

@cli.command()
def seedcerts():
	certs_list = [{'Code': 1,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Programming Language'},
				 {'Code': 2,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Data Cleaning'},
				 {'Code': 3,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Data Analysis'},
				 {'Code': 4,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Data Visualization'},
				 {'Code': 5,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Data Acquisition'},
				 {'Code': 6,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Machine Learning Basics'},
				 {'Code': 7,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Linear Supervised Learning Algorithms'},
				 {'Code': 8,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Non-Linear Supervised Learning Algorithms'},
				 {'Code': 9,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Unsupervised Learning Algorithms'},
				 {'Code': 10,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Clustering Algorithms'},
				 {'Code': 11,
				  'domain': 'Data science',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Data Science (CADS) ',
				  'title': 'Certified Associate in Data Science (CADS) - Deep Learning'},
				 {'Code': 12,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Programming Language'},
				 {'Code': 13,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Data Cleaning'},
				 {'Code': 14,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS)',
				  'title': 'Certified Professional in Data Science (CPDS)- Data Analysis'},
				 {'Code': 15,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Data Visualization'},
				 {'Code': 16,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Data Acquisition'},
				 {'Code': 17,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Machine Learning Basics'},
				 {'Code': 18,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Linear Supervised Learning Algorithms'},
				 {'Code': 19,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Non-Linear Supervised Learning Algorithms'},
				 {'Code': 20,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Unsupervised Learning Algorithms'},
				 {'Code': 21,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Clustering Algorithms'},
				 {'Code': 22,
				  'domain': 'Data science',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Data Science (CPDS) ',
				  'title': 'Certified Professional in Data Science (CPDS) - Deep Learning'},
				 {'Code': 23,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Data Science Project Lifecycle'},
				 {'Code': 24,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Challenges in Data Cleaning'},
				 {'Code': 25,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Challenges in Data Analysis'},
				 {'Code': 26,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Reading visual charts'},
				 {'Code': 27,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Challenges in Data Acquisition'},
				 {'Code': 28,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Machine Learning Basics'},
				 {'Code': 29,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Linear versus non-linear data'},
				 {'Code': 30,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Privacy issues'},
				 {'Code': 31,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Ethical issues'},
				 {'Code': 32,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Structured versus unstructured data'},
				 {'Code': 33,
				  'domain': 'Data science',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Data Science (CLDS) ',
				  'title': 'Certified Leader in Data Science (CLDS) - Data lake'},
				 {'Code': 34,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Programming Language'},
				 {'Code': 35,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Document Object Model'},
				 {'Code': 36,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Styling'},
				 {'Code': 37,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Request-Response cycle'},
				 {'Code': 38,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Application Structure (Example MVC)'},
				 {'Code': 39,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Templates'},
				 {'Code': 40,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Forms'},
				 {'Code': 41,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Databases'},
				 {'Code': 42,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Application Programming Interfaces'},
				 {'Code': 43,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Microservices'},
				 {'Code': 44,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - RESTful Web Services'},
				 {'Code': 45,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Programming Language'},
				 {'Code': 46,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Containers'},
				 {'Code': 47,
				  'domain': 'Web Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Web Development (CAWD) ',
				  'title': 'Certified Associate in Web Development (CAWD) - Front-end frameworks'},
				 {'Code': 48,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Programming Language'},
				 {'Code': 49,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Document Object Model'},
				 {'Code': 50,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Styling'},
				 {'Code': 51,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Request-Response cycle'},
				 {'Code': 52,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Application Structure (Example MVC)'},
				 {'Code': 53,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Templates'},
				 {'Code': 54,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Forms'},
				 {'Code': 55,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Databases'},
				 {'Code': 56,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Application Programming Interfaces'},
				 {'Code': 57,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Microservices'},
				 {'Code': 58,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - RESTful Web Services'},
				 {'Code': 59,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Programming Language'},
				 {'Code': 60,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Containers'},
				 {'Code': 61,
				  'domain': 'Web Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Web Development (CPWD) ',
				  'title': 'Certified Professional in Web Development (CPWD) - Front-end frameworks'},
				 {'Code': 62,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - Front-end frameworks'},
				 {'Code': 63,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - Web Application Project Lifecycle'},
				 {'Code': 64,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - Architectures (Example Microservices)'},
				 {'Code': 65,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - SQL verus NoSQL databases'},
				 {'Code': 66,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - Web Development Frameworks'},
				 {'Code': 67,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - Application Programming Interfaces'},
				 {'Code': 68,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - RESTful Web Services'},
				 {'Code': 69,
				  'domain': 'Web Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Web Development (CLWD) ',
				  'title': 'Certified Leader in Web Development (CLWD) - Containerising'},
				 {'Code': 70,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Programming Language'},
				 {'Code': 71,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Native Applications for Android Platform'},
				 {'Code': 72,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Native Applications for iOS Platform'},
				 {'Code': 73,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Request-Response cycle'},
				 {'Code': 74,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Hybrid applications'},
				 {'Code': 75,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Forms'},
				 {'Code': 76,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Databases'},
				 {'Code': 77,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - Application Programming Interfaces'},
				 {'Code': 78,
				  'domain': 'Mobile Development',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Mobile Development (CAMD) ',
				  'title': 'Certified Associate in Mobile Development (CAMD) - RESTful Web Services'},
				 {'Code': 79,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - Programming Language'},
				 {'Code': 80,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - Native Applications for Android Platform'},
				 {'Code': 81,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - Native Applications for iOS Platform'},
				 {'Code': 82,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - Request-Response cycle'},
				 {'Code': 83,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - Hybrid applications'},
				 {'Code': 84,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - Forms'},
				 {'Code': 85,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - Databases'},
				 {'Code': 86,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD)',
				  'title': 'Certified Professional in Mobile Development (CPMD)- Application Programming Interfaces'},
				 {'Code': 87,
				  'domain': 'Mobile Development',
				  'framework': 'Professional',
				  'sub_domain': 'Certified Professional in Mobile Development (CPMD) ',
				  'title': 'Certified Professional in Mobile Development (CPMD) - RESTful Web Services'},
				 {'Code': 88,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Overview of Native Applications for Android Platform'},
				 {'Code': 89,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Overview Native Applications for iOS Platform'},
				 {'Code': 90,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Request-Response cycle'},
				 {'Code': 91,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Overview of Hybrid applications'},
				 {'Code': 92,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Overview of Progressive Web Applications'},
				 {'Code': 93,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Databases'},
				 {'Code': 94,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Application Programming Interfaces'},
				 {'Code': 95,
				  'domain': 'Mobile Development',
				  'framework': 'Leader',
				  'sub_domain': 'Certified Leader in Mobile Development (CLMD) ',
				  'title': 'Certified Leader in Mobile Development (CLMD) - Classifiers and regressors'},
				 {'Code': 95,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Ensemble Learning'},
				 {'Code': 96,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Detecting Patterns with Unsupervised Learning'},
				 {'Code': 97,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Building Recommender Systems'},
				 {'Code': 98,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Logic Programming'},
				 {'Code': 99,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Heuristic Search Techniques'},
				 {'Code': 100,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Natural Language Processing'},
				 {'Code': 101,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Building A Speech Recognizer'},
				 {'Code': 102,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Object Detection and Tracking'},
				 {'Code': 103,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Artificial Neural Networks'},
				 {'Code': 104,
				  'domain': 'Artificial Intelligence',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Artificial Intelligence (CAAI) ',
				  'title': 'Certified Associate in Artificial Intelligence (CAAI) - Sensing devices'},
				 {'Code': 105,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Inputs and End Points'},
				 {'Code': 106,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Communication and Information Theory'},
				 {'Code': 107,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Internet protocol and transmission control protocol'},
				 {'Code': 108,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Long-Range Communication Systems and Protocols (WAN)'},
				 {'Code': 109,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Routers and Gateways'},
				 {'Code': 110,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Cloud Protocols and Architectures'},
				 {'Code': 111,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Fog Topologies'},
				 {'Code': 112,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - IoT Security'},
				 {'Code': 113,
				  'domain': 'Internet of Things',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Internet of Things (CAIoT) ',
				  'title': 'Certified Associate in Internet of Things (CAIoT) - Hardware virtualization'},
				 {'Code': 114,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Distributed Systems'},
				 {'Code': 115,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - CAP Theorm'},
				 {'Code': 116,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Decentralization'},
				 {'Code': 117,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Cryptography and Technical Foundations'},
				 {'Code': 118,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Mining'},
				 {'Code': 119,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Hash Functions'},
				 {'Code': 120,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Smart Contracts'},
				 {'Code': 121,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Hyperledger'},
				 {'Code': 122,
				  'domain': 'Blockchain',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Blockchain (CABC) ',
				  'title': 'Certified Associate in Blockchain (CABC) - Application-specific blockchains (ASBCs)'},
				 {'Code': 123,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - Distributed Storage'},
				 {'Code': 124,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - Distributed Processing'},
				 {'Code': 125,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - NoSQL'},
				 {'Code': 126,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - Message brokers'},
				 {'Code': 127,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - Distributed File Systems'},
				 {'Code': 128,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - Data Lake'},
				 {'Code': 129,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - Lambda Architecture'},
				 {'Code': 130,
				  'domain': 'Big Data Technologies',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Big Data Technologies (CABDT) ',
				  'title': 'Certified Associate in Big Data Technologies (CABDT) - Privacy'},
				 {'Code': 131,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - Data Encryption'},
				 {'Code': 132,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - Public Key Infrastructure'},
				 {'Code': 133,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - Physical Security Essentials'},
				 {'Code': 134,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - Disaster Recovery'},
				 {'Code': 135,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - Biometrics'},
				 {'Code': 136,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - System Security'},
				 {'Code': 137,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - Access Controls'},
				 {'Code': 138,
				  'domain': 'Cyber Security',
				  'framework': 'Associate',
				  'sub_domain': 'Certified Associate in Cyber Security (CACS) ',
				  'title': 'Certified Associate in Cyber Security (CACS) - Attacks and Countermeasures'}]
		 
	for each in certs_list:
		# db.session.add(Certificate(title=each['title'], domain=each['domain'], sub_domain=each['sub_domain'], framework=each['framework']))	
		# db.session.commit()

		new_cert = Certificate_M(
									title=each['title'],
									code=each['Code'],
									domain=each['domain'],
									framework=each['framework'],
									sub_domain=each['sub_domain']
								)
		new_cert.save()



@cli.command()
def addadmin():
	user = User(firstname='Roshan', lastname='Prakash', email='rosh@ikompass.com', password='rakesh22')
	user.admin = True
	db.session.add(user)	
	db.session.commit()

if __name__ == '__main__':
	cli()